### ISSUE TITLE
Differentiate between user-defined variables and built in variables

### ISSUE THREAD

**Issue by tristan957** [Decodetalkers/tree-sitter-meson#2]
Currently both are just `@variable`

**Comment by Decodetalkers** [comment]
> Currently both are just `@variable`

For example? it is easy to realize, but the buildin variable I already have known is 'true' and 'false'

**Comment by tristan957** [comment]
https://mesonbuild.com/Reference-manual.html#builtin-objects

**Comment by tristan957** [comment]
`meson`, `host_machine`, `build_machine`, `target_machine`.

**Comment by Decodetalkers** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/3662

**Comment by Decodetalkers** [comment]
> Currently both are just `@variable`

Take a look, if there are still something need to add

**Comment by tristan957** [comment]
Thanks!
