### ISSUE TITLE
No highlight group for predicate of if statement

### ISSUE THREAD

**Issue by tristan957** [Decodetalkers/tree-sitter-meson#3]
```meson
var = true
if var # <- no highlight
  #...
endif
```

**Comment by tristan957** [comment]
```meson
var = true
dependency('xx', required: not var) # var is not highlighted
```

**Comment by tristan957** [comment]
```meson
x = [1, 2, 3]
var = x[0] # x is not highlighted
```

**Comment by Decodetalkers** [comment]
> ```meson
> var = true
> if var # <- no highlight
>   #...
> endif
> ```

In nvim-treesitter , I link the "var" to variable, it is your theme defined which color to show the color of vairable

**Comment by Decodetalkers** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/meson/highlights.scm#L56-L72

**Comment by Decodetalkers** [comment]
The color defined is here, they are variable, I think it is your theme think they should be white

**Comment by tristan957** [comment]
I get "No highlight groups found" when I do `:TSHighlightCapturesUnderCursor` in neovim

**Comment by tristan957** [comment]
This seems fixed.
